cloudwego/sonic-rs

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, README.md, README_ZH.md, assets/pngs/flamegraph.sh, src/serde/de.rs, src/util/mod.rs, src/value/node.rs
=> feat: make utf-8 validation in default

src/value/index.rs
=> feat: impl Index and IndexMut for &String and &FastStr

src/value/mod.rs
=> feat: export RawValue at value module #42

Cargo.lock, Cargo.toml, examples/lazyvalue.rs, fuzz/Cargo.lock, fuzz/fuzz_targets/from_slice.rs, src/format.rs, src/lazyvalue/mod.rs, src/lazyvalue/owned.rs, src/lazyvalue/value.rs, src/lib.rs, src/prelude.rs, src/serde/mod.rs, src/util/simd/mod.rs, src/util/simd/neon.rs, src/value/array.rs, src/value/mod.rs, src/value/object.rs, src/value/tls_buffer.rs, src/value/value_trait.rs, src/writer.rs
=> fix: add default, debug, diplay for lazyvalue

README.md
The notation for referring to the sonic-rs dependency in README.md has been corrected. It now correctly includes double quotes around the version number for compatibility with the dependency file format.
en:
zh(optional):
=> doc: Update sonic-rs dependency notation in README

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, scripts/fuzz.sh, src/util/num/mod.rs
Fixed parse number conner case and make fuzzing test longer.
=> fix ci and parse float number bug

README.md, README_ZH.md, src/lazyvalue/get.rs, src/parser.rs, src/prelude.rs
Simplify readme, fix typos and fix an error in debug mode
=> Simplify readme,  fix an error when using get API in debug mode

src/parser.rs, src/serde/de.rs, src/serde/mod.rs
Fix problems in deserialize map likes #73
=> fix: should checking ending when visit_map

src/lazyvalue/value.rs
docs: add LazyValue convert to serde_json::Value examples
=> doc: add LazyValue convert to serde_json::Value examples

src/serde/mod.rs, src/serde/ser.rs
=> fix: missed quote when serialize float key

README.md
=> docs(README): fix broken `config.toml` link

src/pointer/point.rs
fix https://github.com/cloudwego/sonic-rs/issues/83
=> perf: remove unnecessary allocation in `pointer!()` macro

fuzz/fuzz_targets/from_slice.rs, scripts/fuzz.sh, src/index.rs, src/parser.rs, src/serde/de.rs
fix parse `0` into u128 and enhanced the fuzzing tests
=> fix: deserialize 0 into u128

examples/serde.rs, examples/testdata/person.json, src/error.rs, src/lib.rs, src/serde/de.rs, src/serde/mod.rs
closes https://github.com/cloudwego/sonic-rs/issues/43
ref: https://github.com/simd-lite/simd-json/blob/dd7fc44f5526e3e2abe0ebba53bc1faed501a128/src/serde.rs#L143C8-L143C19
=> feat: support `from_reader`

.gitignore, Cargo.toml, benchmarks/benches/common.rs, benchmarks/benches/deserialize_value.rs, benchmarks/benches/serialize_value.rs, fuzz/fuzz_targets/from_slice.rs, scripts/sanitize.sh, src/lazyvalue/iterator.rs, src/parser.rs, src/pointer/point.rs, src/serde/de.rs, src/util/utf8.rs, src/value/from.rs, src/value/node.rs, src/writer.rs
en:
zh(optional): 
1. Fix the bug in Value when use_raw, and add a feature
2. Add benchmark
=> fix: fix value and add benchmarks

Cargo.toml, fuzz/fuzz_targets/from_slice.rs, scripts/fuzz.sh, src/serde/de.rs
=> bump 0.3.15

Cargo.toml
=> chore: missed version

sonic-number/Cargo.toml, sonic-simd/Cargo.toml
=> chore: adjust description

Cargo.toml, sonic-number/Cargo.toml, sonic-simd/Cargo.toml, src/reader.rs, src/value/array.rs, src/value/node.rs, src/value/object.rs
=> fix: unnecessary utf8 check in unchecked apis and use ref_cast replace transmute

README_ZH.md
Small PR - fixes the Cargo config reference in `README_ZH.md`.
en:
zh(optional):
=> fix: update config reference

src/error.rs, src/lib.rs
=> fix: export error module

src/writer.rs
=> feat: impl `WriteExt` for `&mut BytesMut`

examples/json_filter.rs, fuzz/src/lib.rs, src/lazyvalue/iterator.rs, src/parser.rs
=> opt: use cow in json iterator

.github/workflows/ci.yml, .github/workflows/dependency-review.yaml, src/lazyvalue/iterator.rs, src/parser.rs
=> ci: use aarch64

src/serde/de.rs, src/value/node.rs
=> fix: comments

.github/workflows/ci.yml
=> fix: nightly ci

src/value/object.rs
fix: support get or insert for object index mut
en:
Like data structures such as serde map and hashmap, when obtaining variable references through [key] indexes, the semantics of obtaining or inserting are supported, and sonic null values ​​are inserted by default.
zh(optional):
=> fix: support get or insert for object index mut

.github/workflows/ci.yml, Cargo.toml, src/serde/mod.rs, src/value/node.rs
=> ci: test fallback impl for wasm

.github/PULL_REQUEST_TEMPLATE.md, Cargo.toml, src/error.rs, src/lib.rs, src/parser.rs, src/prelude.rs, src/reader.rs, src/serde/de.rs, src/serde/ser.rs
en: export more low-level apis
zh(optional):
=> chore: export more apis

Cargo.toml, examples/get_many.rs, examples/handle_error.rs, src/error.rs, src/index.rs, src/lazyvalue/get.rs, src/lazyvalue/iterator.rs, src/lazyvalue/ser.rs, src/parser.rs, src/pointer/point.rs, src/pointer/tree.rs, src/serde/de.rs, src/serde/mod.rs, src/serde/number.rs, src/serde/ser.rs, src/util/arch/mod.rs, src/value/array.rs, src/value/node.rs, src/value/ser.rs, src/value/value_trait.rs
feat: support api `end` for deserializer to check trailing chars
ref: https://github.com/serde-rs/json/blob/8a56cfa6d0a93c39ee4ef07d431de0748eed9028/src/de.rs#L146
en:
zh(optional):
=> feat: support api for deserializer to check trailing chars

examples/handle_error.rs, examples/iterator.rs, src/error.rs, src/lazyvalue/iterator.rs, src/reader.rs, src/serde/mod.rs, src/value/node.rs
=> fix: correct column number in error message (#178)
