src/lazyvalue/iterator.rs, src/parser.rs, src/pointer/point.rs, src/pointer/tree.rs, src/serde/de.rs, src/serde/ser.rs, src/util/num/mod.rs, src/util/string.rs, src/value/node.rs
I used clippy to activate some lints to apply some fixes.
Nothing major. Mostly stylistic and idiomatic fixes.
=> Clippy fixes

.github/workflows/ci.yml, fuzz/Cargo.lock, fuzz/fuzz_targets/from_slice.rs, src/parser.rs, src/reader.rs, src/util/num/mod.rs, src/value/node.rs
=> fix(dom): invalid memcopy and trailing char bug in fuzzer

Cargo.lock, Cargo.toml, README.md, README_ZH.md, benches/deserialize_struct.rs, benches/deserialize_value.rs, docs/performance.md, fuzz/Cargo.lock, src/util/num/mod.rs, src/value/node.rs
=> fix: parse max u64 and enable float_roundtrip for serde-json

Cargo.lock, Cargo.toml, README.md, README_ZH.md, src/input.rs, src/lazyvalue/get.rs, src/lazyvalue/value.rs, src/lib.rs, src/parser.rs, src/serde/mod.rs, src/serde/number.rs, src/util/string.rs, src/util/utf8.rs, src/value/index.rs, src/value/node.rs, src/value/value_trait.rs, src/writer.rs
Refactor the writerext trait to support `&mut T`. Fixed  #26
=> fix writerext and validate utf-8 in get apis

Cargo.toml, src/error.rs, src/lazyvalue/de.rs, src/lazyvalue/get.rs, src/lazyvalue/iterator.rs, src/lazyvalue/owned.rs, src/lazyvalue/ser.rs, src/lazyvalue/value.rs, src/parser.rs, src/serde/de.rs, src/value/de.rs
Origin `LazyValue` has a `UnsafeCell`, to be used for parsing string which has escaped chars. This makes the parsing lazy but also makes it `!Sync`.
In the new `LazyValue`, we will first parse the string which has escaped chars and store it in the `Arc<str>`. It will be `Sync`.
=> fix: make lazyvalue sync

Cargo.lock, src/error.rs, src/lazyvalue/get.rs, src/parser.rs, src/util/arch/aarch64.rs, src/util/simd/avx2.rs, src/util/simd/bits.rs, src/util/simd/mod.rs, src/util/simd/neon.rs, src/util/simd/sse2.rs, src/util/simd/traits.rs, src/util/simd/v128.rs, src/util/simd/v256.rs, src/util/simd/v512.rs, src/util/string.rs, src/value/node.rs, src/value/tls_buffer.rs
Optimize and refactor
1. implement faster bitmask for NEON vector.[reference](https://community.arm.com/arm-community-blogs/b/infrastructure-solutions-blog/posts/porting-x86-vector-bitmask-optimizations-to-arm-neon)
2. refactor the codes of portable SIMD to support faster bitmap above.
3. deal with the different endianness when using bitmask for vector 
benchmark data:
deserialize_struct
```
twitter/sonic_rs::from_slice_unchecked
time:   [416.42 µs 417.61 µs 418.95 µs]
change: [-8.1303% -7.4773% -6.8652%] (p = 0.00 < 0.05)
Performance has improved.
Found 19 outliers among 100 measurements (19.00%)
9 (9.00%) high mild
10 (10.00%) high severe
twitter/sonic_rs::from_slice
time:   [437.19 µs 438.17 µs 439.25 µs]
change: [-10.175% -9.5169% -8.8809%] (p = 0.00 < 0.05)
Performance has improved. …
```
=> opt: use faster NEON bitmask and fix skip number bug

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, fuzz/fuzz_targets/from_slice.rs, src/error.rs, src/index.rs, src/lazyvalue/value.rs, src/parser.rs, src/serde/de.rs, src/serde/mod.rs, src/serde/ser.rs, src/util/num/mod.rs, src/value/from.rs, src/value/node.rs, src/value/object.rs, src/value/partial_eq.rs, src/value/ser.rs
Fix the deserialize into `bytes:Bytes` bug and Clippy warnings
=> fix: deserialize into Bytes bug and clippy

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, src/parser.rs, src/serde/de.rs, src/serde/mod.rs, src/util/arch/mod.rs
=> WIP: fix some bugs

src/input.rs, src/lib.rs
=> Re-export `Index`, `JsonInput` and `FastStr`

scripts/sanitize.sh, src/value/array.rs, src/value/node.rs, src/value/object.rs
When constructing a new object or array, it should not be a root value because it does not need a shared allocator.
=> fix: possible use-after-free bug in Array::new and Object::new

Cargo.toml, src/lazyvalue/get.rs, src/lazyvalue/iterator.rs, src/lazyvalue/value.rs, src/lib.rs, src/reader.rs, src/serde/de.rs, src/util/private.rs, src/value/de.rs
we only use `Read` for all string/bytes like json inputs for user-friendliness.  In the future, we will use `IoRead` for IO inputs.
=> chore: simplify  `Read` api and export

Cargo.toml, src/serde/de.rs, src/serde/mod.rs
=> fix: deserialize JSON key into non-string serde types

.github/workflows/ci.yml, Cargo.toml, benches/deserialize_struct.rs, benches/deserialize_value.rs, benches/schema/Cargo.toml, benches/schema/README.md, benches/schema/licences/LICENSE-json-benchmark, benches/schema/src/canada.rs, benches/schema/src/citm_catalog.rs, benches/schema/src/color.rs, benches/schema/src/empty.rs, benches/schema/src/enumstr.rs, benches/schema/src/lib.rs, benches/schema/src/prim_str.rs, benches/schema/src/twitter.rs, benches/serialize_struct.rs, benches/serialize_value.rs, examples/json_number.rs, scripts/sanitize.sh, src/lazyvalue/iterator.rs, src/parser.rs, src/reader.rs, src/serde/mod.rs, src/value/node.rs
1. Fix a memory leak when using `sonic-rs::Value`
2. Make ci can run on windows
3. Fix `slice_ref` panic when using `faststr 0.2.20`
=> fix memory leaks and support windows ci

.gitignore, Cargo.toml, benches/value_operator.rs, src/input.rs, src/lazyvalue/iterator.rs, src/lib.rs, src/parser.rs, src/serde/de.rs, src/serde/mod.rs, src/util/arch/mod.rs, src/util/mod.rs, src/util/string.rs, src/value/node.rs, src/value/object.rs
support stream decoder and remove some dependencies
=> feat: support stream decoder

src/value/node.rs
=> fix: missed symbol in low rustc version

src/lib.rs, src/serde/de.rs
fix: export MapAccess, SeqAccess
导出 `MapAccess`、`SeqAccess`
en: export `MapAccess` and `SeqAccess` for the convenience of users.
zh(optional): 导出 `MapAccess`、`SeqAccess` 便于用户使用。
=> fix: export MapAccess, SeqAccess

Cargo.toml, fuzz/Cargo.toml, fuzz/src/lib.rs, src/lazyvalue/owned.rs, src/parser.rs, src/serde/de.rs
=> fix: should validate when parsing into lazyvalue

Cargo.toml, src/lazyvalue/owned.rs
=> fix: memory leak in owned lazyvalue

src/format.rs
=> chore: fix comments in write_string_fast

sonic-simd/src/v128.rs, src/serde/de.rs, src/value/node.rs
fix: Fix compilation on 32-bit architectures
`sonic-rs` in its current form fails to compile for 32-bit architectures, such as `armv7-unknown-linux-musleabihf`. While niche, I still thing it's a worthwhile thing to support.
It also fixes some logic bugs uncovered by compiling it to 32-bit.
Bug 1: Documenting a maximum of 2GB and then restricting to 1 << 32 (which evaluates to 4GB instead)
Bug 2: Transmuting a `&[u8; 8]` into a `u64` which won't contain a copy of the data and instead just the pointer, technically producing a dangling pointer that is never dereferenced
---
Please let me know if I should add a GitHub Actions workflow that executes `cross test --target=armv7-unknown-linux-musleabihf`.
=> fix: Fix compilation of fallback backend and minor issues

Cargo.toml, benchmarks/benches/value_operator.rs, src/index.rs, src/lazyvalue/value.rs, src/value/from.rs, src/value/macros.rs, src/value/node.rs, src/value/object.rs, src/value/partial_eq.rs, src/value/ser.rs
perf: use hashmap in owned object to optimize search performance
en:
Sonic has a disadvantage compared to serde. Its object type search and insertion performance is O(n), which is determined by the underlying data structure.
To align performance to O(1), sonic objects also need to use hashmaps.
Specifically, sonic's data structures are divided into shared and owned. The former is used in the parse stage and has many internal optimizations. It is not suitable to directly replace the data structure for the time being.
The owned data structure can be directly replaced by hashmap for maintenance. At the same time, in order to support the sort keys function, btreemap is used to make performance tradeoffs for sorting and other operations.
zh(optional):
=> perf: use hashmap in owned object to optimize search performance

src/value/node.rs
=> safety: check the node idx

Cargo.toml, README.md, scripts/sanitize.sh, src/util/string.rs
Add `sanitize` feature to avoid false-positive cases when using LLVM-sanitizer in release mode.
Note: we do not disable the `cross-page access` optimization in serialize because it may cause 30% performance-loss
```
Running benches/serialize_struct.rs (target/release/deps/serialize_struct-0c18a33db440f245)
twitter/sonic_rs::to_string
time:   [399.60 µs 399.80 µs 400.02 µs]
change: [+32.975% +33.090% +33.201%] (p = 0.00 < 0.05)
Performance has regressed.
Found 10 outliers among 100 measurements (10.00%)
4 (4.00%) high mild
6 (6.00%) high severe
canada/sonic_rs::to_string
time:   [3.3139 ms 3.3149 ms 3.3161 ms]
change: [-2.8470% -2.7749% -2.7149%] (p = 0.00 < 0.05)
Performance has improved.
Found 12 outliers among 100 measurements (12.00%)
4 (4.00%) high mild
8 (8.00%) high severe …
```
=> feat: add sanitize feature

.github/workflows/ci.yml, src/value/node.rs
=> chore: add ub notes

.github/workflows/ci.yml, .github/workflows/security.yml, Cargo.toml, scripts/test.sh, src/format.rs, src/serde/mod.rs
=> feat: support serialize floating point numbers without trailing zeros
